### ISSUE TITLE
Jenkins can not generate performance report thru json file.

### ISSUE THREAD

**Issue by XGWang0** [TrueDub/cucumber-performance#10]
Hi TrueDuber:

Firstly, i don't know if my usage of cucumber performance report is incorrect.  
but when i follows the usage to generate the report of performance , i got nothing.
There is my json file, 
----------------------------------
[
  {
    "keyword": "Feature",
    "name": "Hello World Feature",
    "description": "In order to ensure that my installation works\nAs a Developer\nI want to run a quick Cucumber test",
    "id": "hello-world-feature",
    "uri": "features/unitest1.feature",
    "elements": [
      {
        "keyword": "Scenario",
        "name": "Hello World Scenario",
        "description": "",
        "tags": [
          {
            "name": "@test"
          }
        ],
        "steps": [
          {
            "keyword": "Given ",
            "name": "The Action is Hello",
            "doc_string": {
              "value": "describe \"an example\" do\n   it \"has not yet been implemented\"\nend"
            },
            "output": [
              "This is before hook."
            ],
            "result": {
              "status": "failed",
              "error_message": "Your block takes 1 argument, but the Regexp matched 2 arguments. (Cucumber::ArityMismatchError)\nfeatures/step_denfinitions/step_steps.rb:3:in `/The Action is ([A-z]*)/'\nfeatures/unitest1.feature:8:in `Given The Action is Hello'",
              "duration": 198435
            }
          },
          {
            "keyword": "When ",
            "name": "The Subject is World",
            "result": {
              "status": "skipped"
            }
          },
          {
            "keyword": "Then ",
            "name": "The Greeting is Hello, World",
            "result": {
              "status": "skipped"
            },
            "output": [
              "This is after hook."
            ]
          }
        ]
      },
      {
        "keyword": "Scenario",
        "name": "Test World Scenario",
        "description": "",
        "steps": [
          {
            "keyword": "Given ",
            "name": "The Action is Test",
            "output": [
              "This is before hook."
            ],
            "result": {
              "status": "passed",
              "duration": 24000
            }
          },
          {
            "keyword": "When ",
            "name": "The Subject is World",
            "result": {
              "status": "passed",
              "duration": 17540
            }
          },
          {
            "keyword": "Then ",
            "name": "The Greeting is Test, World",
            "result": {
              "status": "passed",
              "duration": 20401531
            },
            "output": [
              "This is after hook."
            ]
          }
        ]
      }
    ]
  },
  {
    "keyword": "Feature2",
    "name": "Hello World Feature",
    "description": "In order to ensure that my installation works\nAs a Developer\nI want to run a quick Cucumber test",
    "id": "hello-world-feature",
    "uri": "features/unitest1.feature2",
    "elements": [
      {
        "keyword": "Scenario",
        "name": "Hello World Scenario",
        "description": "",
        "tags": [
          {
            "name": "@test"
          }
        ],
        "steps": [
          {
            "keyword": "Given ",
            "name": "The Action is Hello",
            "doc_string": {
              "value": "describe \"an example\" do\n   it \"has not yet been implemented\"\nend"
            },
            "output": [
              "This is before hook."
            ],
            "result": {
              "status": "failed",
              "error_message": "Your block takes 1 argument, but the Regexp matched 2 arguments. (Cucumber::ArityMismatchError)\nfeatures/step_denfinitions/step_steps.rb:3:in `/The Action is ([A-z]*)/'\nfeatures/unitest1.feature:8:in `Given The Action is Hello'",
              "duration": 198435
            }
          },
          {
            "keyword": "When ",
            "name": "The Subject is World",
            "result": {
              "status": "skipped"
            }
          },
          {
            "keyword": "Then ",
            "name": "The Greeting is Hello, World",
            "result": {
              "status": "skipped"
            },
            "output": [
              "This is after hook."
            ]
          }
        ]
      },
      {
        "keyword": "Scenario",
        "name": "Test World Scenario",
        "description": "",
        "steps": [
          {
            "keyword": "Given ",
            "name": "The Action is Test",
            "output": [
              "This is before hook."
            ],
            "result": {
              "status": "passed",
              "duration": 24000
            }
          },
          {
            "keyword": "When ",
            "name": "The Subject is World",
            "result": {
              "status": "passed",
              "duration": 17540
            }
          },
          {
            "keyword": "Then ",
            "name": "The Greeting is Test, World",
            "result": {
              "status": "passed",
              "duration": 20401531
            },
            "output": [
              "This is after hook."
            ]
          }
        ]
      }
    ]
  }
]
------------------------------------------------------
I put the json into test folder of job workspace

Then, i configure the cucumber performance setting,  
Json Reports Path   >  test
Json file name -> result.json (this is the real name of json file in test folder)
Number of items to display -> 2

After above all setting, i run a job and try to see the cucumber performance report, i got nothing

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
