### ISSUE TITLE
Cannot display performance graph 

### ISSUE THREAD

**Issue by ssnyder** [TrueDub/cucumber-performance#9]
I've got some successful builds, but the graph is blank.  The trending sidebar is also taking the full width of the window, and the performance information shows up underneath.

I see the following errors when running this in FF (same/similar errors when using chrome):
TypeError: box.value is undefined hudson-behavior.js:2204
TypeError: element.attachEvent is not a function prototype.js:5717
TypeError: element.attachEvent is not a function prototype.js:5708
TypeError: element.dispatchEvent is not a function prototype.js:5798
TypeError: jQuery(...).highcharts is not a function performanceGraph.js:4
TypeError: $(...).observe is not a function hudson-behavior.js:1137
TypeError: $(...).getElementsBySelector is not a function

The reports are generated because the tabular information is available, it's the graph drawing that appears to be the problem.  My console log is as follows:
[CucumberPerfRecorder] Starting Cucumber Performance Report generation...
[CucumberPerfRecorder] Reporting on performance for trunk #205
[CucumberPerfRecorder] detected master build 
looking in /var/lib/jenkins/jobs/trunk/workspace/log
found files
found files
found files
found files
found files
found files
found files
found files
found files
found files
found files
[CucumberPerfRecorder] running project reports on 11 builds
[CucumberPerfRecorder] project report generation complete
Publishing rcov report...
[CucumberReportPublisher] Compiling Cucumber Html Reports ...
[CucumberReportPublisher] copying all json files from: /var/lib/jenkins/jobs/trunk/workspace/log to reports directory: /var/lib/jenkins/jobs/trunk/builds/205/cucumber-html-reports
[CucumberReportPublisher] Found the following number of json files: 1
[CucumberReportPublisher] 0. Found a json file: cucumber.json
[CucumberReportPublisher] Generating HTML reports

Please let me know what additional information you need to help track this down.  Thanks.

**Comment by tombutt** [comment]
I can say I'm seeing something similar.  I get the Feature details, and I can view all of the textual reporting, but the graph and  charts are not visible.

**Comment by TrueDub** [comment]
Due to pressures of time, along with lack of access to a large-scale Cucumber project to facilitate testing, I'm no longer in a position to maintain this project. Thank you for your feedback.

If required, I suggest you open an issue on the jenkinsci repo page for the plugin - https://github.com/jenkinsci/cucumber-performance-plugin
